image: gcr.io/kaniko-project/executor:debug

stages:
  - build-and-push
  - deploy

build-and-push-job:
  stage: build-and-push
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8} --destination $CI_REGISTRY_IMAGE:latest

deploy-nautilus:
  only:
    refs:
      - master
  needs:
    - build-and-push
  stage: deploy
  image: bitnami/kubectl
  environment:
    name: production
  script:
    - kubectl set image -n kube-system deployment nautilus-portal nautilus-portal=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
