image:
  name: alpine/helm:3.10.1
  entrypoint: ["/bin/sh", "-c"]

deploy-helm:
  script:
    - apk add gettext
    - envsubst < values.template.yaml > values.yaml
    - helm upgrade visualnet-api ./chart --cleanup-on-fail -i -n alto --version=0.1.0 -f values.yaml
  environment:
    name: openalto
