stages:
  - assemble
  - deploy

push:
  stage: assemble
  image: gcr.io/kaniko-project/executor:debug
  script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8} --destination $CI_REGISTRY_IMAGE:latest

deploy:
  only:
    refs:
      - master
  needs:
    - push
  stage: deploy
  image: bitnami/kubectl
  environment:
    name: production
  script:
    - kubectl set image deployment visualnet-api visualnet-api=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
