{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: "/"
        {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.applicationName }}
            port:
              number: 4000
        {{- else }}
        backend:
          serviceName: {{ .Values.applicationName }}
          servicePort: 4000
        {{- end }}
  tls:
  - hosts:
    - {{ .Values.domain }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.applicationName }}
  name: {{ .Values.applicationName }}
spec:
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: {{ .Values.applicationName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.applicationName }}
  name: {{ .Values.applicationName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
          image: gitlab-registry.nrp-nautilus.io/gd/visualnet-api
          name: {{ .Values.applicationName }}
      restartPolicy: Always
status: {}
